services:
  - type: web
    name: conference-proceedings
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /api/state